models/post.py
import sqlite3


class Post:
    def __init__(self, conn: sqlite3.Connection):
        self.conn = conn

    # ---------CRUD-----------
    def all(self):
        cur = self.conn.execute(
            """
            SELECT posts.id,
                   posts.title,
                   posts.content,
                   posts.views,
                   posts.likes,
                   posts.created_at,
                   posts.updated_at,
                   posts.author_id,
                   users.name
            FROM posts
                     JOIN users ON users.id = posts.author_id
            """,
        )
        return [dict(r) for r in cur.fetchall()]

    def get(self, post_id):
        cur = self.conn.execute(
            """SELECT *
               FROM posts
               WHERE id = ?""", [post_id],
        )
        row = cur.fetchone()
        return dict(row) if row else None

    def create(self, title, content, author_id=None):
        cur = self.conn.execute(
            """
            INSERT
            INTO posts(title, content, author_id)
            VALUES (?, ?, ?) """,
            [title, content, author_id],
        )
        self.conn.commit()
        return cur.lastrowid

    def update(self, post_id, title, content):
        cur = self.conn.execute(
            """
            UPDATE
                posts
            SET title      = ?,
                content    = ?,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ?""",
            [title, content, post_id],
        )
        self.conn.commit()
        return self.get(post_id) if cur.rowcount else None

    def delete(self, post_id):
        cur = self.conn.execute(
            """DELETE
               FROM posts
               WHERE id = ?""", [post_id],
        )
        self.conn.commit()
        return cur.rowcount > 0

    def increment_views(self, post_id):
        cur = self.conn.execute(
            """
            UPDATE posts
            SET views = views + 1
            WHERE id = ?
            """,
            [post_id],
        )

        self.conn.commit()
        return cur.rowcount > 0


    def get_by_author(self, author_id):
        cur = self.conn.execute(
            """
            SELECT *
            FROM posts
            WHERE author_id = ?
            """,
            [author_id],
        )
        return [dict(r) for r in cur.fetchall()]


    def search(self, query):
        search_term = f"%{query}%"
        cur = self.conn.execute(
            """
            SELECT *
            FROM posts
            WHERE title LIKE ?
               OR content LIKE ?
            """,
            [search_term, search_term],
        )
        return [dict(r) for r in cur.fetchall()]


    def get_top_viewed(self, limit=10):
        '''
        Вернуть какое-то количество самых популярных статей (10, 15, ...)
        '''
        cur = self.conn.execute(
            """
            SELECT *
            FROM posts
            ORDER BY views DESC LIMIT ?
            """, [limit],
        )
        return [dict(r) for r in cur.fetchall()]


    def count_all(self):
        '''
        Возвращает кол-во статей на сайте
        '''
        cur = self.conn.execute("SELECT COUNT(*) as count FROM posts")
        row = cur.fetchone()
        return row["count"] if row else 0

blueprints/posts.py
from flask import Blueprint
from controllers.posts import PostsController

def create_posts_blueprint(controller: PostsController):
    bp = Blueprint("posts", __name__, url_prefix="/posts")
    
    bp.add_url_rule("/", "index", controller.index, methods=["GET"])
    bp.add_url_rule("/<int:post_id>", "show", controller.show, methods=["GET"])
    bp.add_url_rule("/create", "create", controller.create, methods=["GET", "POST"])
    bp.add_url_rule("/<int:post_id>/edit", "edit", controller.edit, methods=["GET", "POST"])
    bp.add_url_rule("/<int:post_id>/delete", "delete", controller.delete, methods=["POST"])
    return bp

controllers/posts.py
from flask import request, render_template, flash, redirect, url_for, g

from models.post import Post
from utils.decorators import login_required


class PostsController:
    """
    Контроллер не знает ни об app | g
    Он получает функции, возвращает соединения
    """

    def __init__(self, get_db):
        self.get_db = get_db

    def index(self):
        conn = self.get_db()
        model = Post(conn)
        items = model.all()
        return render_template("posts/index.html", title="Посты", items=items)

    def show(self, post_id):
        conn = self.get_db()
        model = Post(conn)
        post = model.get(post_id)
        if not post:
            return render_template("errors/404.html", title="Не найдено")
        model.increment_views(post_id)
        post["views"] += 1
        return render_template(
            "posts/show.html", title=post["title"], post=post,
        )

    @login_required
    def create(self):
        if request.method == "GET":
            return render_template("/posts/create.html", title="Новый пост")
        title = (request.form.get("title") or "").strip()
        content = (request.form.get("content") or "").strip()
        error = False
        if not title or not content:
            flash("Не заполнены все поля", "warning")
            error = True
        if len(title) < 5:
            flash("Заголовок должен быть не менее 5 символов", "warning")
            error = True
        if len(content) < 10:
            flash("Текст должен быть не менее 10 символов", "warning")
            error = True

        if error:
            return render_template(
                "/posts/create.html",
                title="Новый пост",
                form={"title": title, "content": content},
            )
        conn = self.get_db()
        model = Post(conn)

        author_id = g.user["id"] if hasattr(g, "user") and g.user else None

        post_id = model.create(title, content, author_id)
        return redirect(url_for("posts.show", post_id=post_id))

    @login_required
    def edit(self, post_id):
        conn = self.get_db()
        model = Post(conn)
        post = model.get(post_id)

        if not post:
            flash("Статья не найдена", "warning")
            return redirect(url_for("posts.index"))

        if post.get("author_id") != (g.user["id"] if hasattr(g, "user") and
                                                     g.user else None):
            flash("Вы не можете редактировать чужие статьи", "danger")
            return redirect(url_for("posts.show", post_id=post_id))

        if request.method == "GET":
            return render_template(
                "/posts/update.html",
                title=f"Редактирование: {post['title']}",
                post=post,
            )
        title = (request.form.get("title") or "").strip()
        content = (request.form.get("content") or "").strip()
        if not title or not content:
            flash("Не заполнены все поля", "warning")
            return render_template(
                "/posts/update.html",
                title=f"Редактирование: {post['title']}",
                post=post,
            )
        model.update(post_id, title, content)
        flash("Пост успешно обновлён", "success")
        return redirect(url_for('posts.show', post_id=post_id))

    @login_required
    def delete(self, post_id):
        conn = self.get_db()
        model = Post(conn)
        post = model.get(post_id)
        if not post:
            flash("Статья не найдена", "warning")
            return redirect(url_for("posts.index"))

        if post.get("author_id") != (g.user["id"] if hasattr(g, "user") and
                                                     g.user else None):
            flash("Вы не можете удалять чужие статьи", "danger")
            return redirect(url_for("posts.show", post_id=post_id))

        model.delete(post_id)
        flash("Пост удалён", "info")
        return redirect(url_for("posts.index"))

templates/posts/create.html
{% extends "base.html" %} 
{% block content %}
<form action="{{url_for('posts.create')}}" method="post">
    <div>
        <label for="title">Название</label>
        <input type="text" name="title" id="title"/>
    </div>
    <div>
        <label for="content">Содержимое</label>
        <textarea name="content" id="content"></textarea>
    </div>
    <div>
        <button type="submit">Публиковать</button>
    </div>
</form>
{% endblock %}

templates/posts/index.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ title }}</h1>

    {% include 'components/flash.html' %}

    {% if items %}
        {% for post in items %}
            <article class="post-card">
                <div class="post-card-header">
                    <h2>
                        <a href="{{ url_for('posts.show', post_id=post['id']) }}">{{ post['title'] }}</a>
                    </h2>
                    <h3>
                        <a href="{{ url_for('auth.profile', user_id=post['author_id']) }}">
                            {{ post['name'] }}</a>
                    </h3>
                </div>
                <div class="post-card-preview">
                    {{ post['content'][:100] }}...
                </div>
                <div class="post-card-bottom">
                    <div class="post-card-bottom-left">
                        <span><i class="fa-solid fa-heart"></i>{{ post['likes'] }}</span>
                        <span><i class="fa-solid fa-eye"></i>{{ post['views'] }}</span>
                    </div>
                    <div class="post-card-bottom-right">
                    <span>
                        {{ post['created_at'] if post['created_at'] else "неизв." }}
                    </span>
                    </div>
                </div>
            </article>
        {% endfor %}
    {% else %}

    {% endif %}
{% endblock %}

templates/posts/show.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ post['title'] }}</h1>
    <p>{{ post['content'] }}</p>

    {% if g.user %}
        <div class="like-btn">
            <button class="like-btn__btn" data-post-id="{{ post['id'] }}" type="button">
                <i class="like-icon fa-solid fa-heart"></i>
                <span class="like-count">{{ post['likes'] }}</span>
            </button>
        </div>
    {% else %}
        <div>
            <i class="fa-solid fa-heart"></i>
            <span class="like-count">{{ post['likes'] }}</span>
        </div>
    {% endif %}

    {% if g.user == post['author_id'] %}
        <a href="{{ url_for('posts.edit', post_id=post["id"]) }}">Редактировать</a>

        <form action="{{ url_for('posts.delete', post_id=post["id"]) }}" method="post">
            <button type="submit">Удалить</button>
        </form>
    {% endif %}
{% endblock %}

{% block script %}
    <script src="{{ url_for('static', filename='js/likes.js') }}"></script>
{% endblock %}

templates/posts/update.html
{% extends "base.html" %}
{% block content %}
<form action="{{url_for('posts.edit', post_id = post.id)}}" method="post">
    <div>
        <label for="title">Название</label>
        <input type="text" name="title" id="title" value="{{post.title}}"/>
    </div>
    <div>
        <label for="content">Содержимое</label>
        <textarea name="content" id="content">{{post.content}}</textarea>
    </div>
    <div>
        <button type="submit">Редактировать</button>
    </div>
</form>
{% endblock %}